import { AppSettings, Prices, Weights, CustomProduct } from "../types";

export interface StandardProductDefinition {
  id: string;
  name: string;
  subLabel?: string;
  category: "slabs" | "hex_fence" | "i_piles" | "s_piles" | "pipes" | "basins" | "other";
  categoryLabel: string;
  unit: string;
  priceKey: keyof Prices;
  costKey: keyof Prices;
  weightKey?: keyof Weights;
  fixedWeight?: number;
  weightUnit: string;
  isTIS?: boolean;
}

export interface UnifiedCatalogItem {
  id: string;
  name: string;
  subLabel?: string;
  category: "slabs" | "hex_fence" | "i_piles" | "s_piles" | "pipes" | "basins" | "other";
  categoryLabel: string;
  unit: string;
  cost: number;
  price: number;
  markup: number;
  weight: number;
  weightUnit: string;
  isTIS?: boolean;
  isCustom: boolean;
  fieldKey?: keyof Prices;
  weightKey?: keyof Weights;
}

export const CATEGORY_DEFINITIONS: { id: string; label: string; dotColor: string }[] = [
  { id: "all", label: "ทั้งหมด", dotColor: "bg-neutral-600" },
  { id: "slabs", label: "แผ่นพื้น", dotColor: "bg-red-600" },
  { id: "hex_fence", label: "เสารั้ว & หกเหลี่ยม", dotColor: "bg-amber-500" },
  { id: "i_piles", label: "เสาเข็ม I", dotColor: "bg-red-700" },
  { id: "s_piles", label: "เสาเข็มสี่เหลี่ยม S", dotColor: "bg-orange-600" },
  { id: "pipes", label: "ท่อ คสล.", dotColor: "bg-emerald-600" },
  { id: "basins", label: "บ่อพัก คสล.", dotColor: "bg-indigo-600" },
  { id: "other", label: "สินค้าสั่งทำ / อื่นๆ", dotColor: "bg-purple-600" },
];

export const STANDARD_PRODUCTS: StandardProductDefinition[] = [
  // 1. Slabs
  {
    id: "normalBoardPrice",
    name: "แผ่นพื้นท้องเรียบธรรมดา",
    subLabel: "ฐานลวด 4 เส้น",
    category: "slabs",
    categoryLabel: "กลุ่มราคาแผ่นพื้นคอนกรีตอัดแรง (บาท / ตร.ม.)",
    unit: "บ./ตร.ม.",
    priceKey: "normalBoardPrice",
    costKey: "normalBoardPrice",
    weightKey: "slab",
    weightUnit: "กก./ตร.ม.",
  },
  {
    id: "mocBoardPrice",
    name: "แผ่นพื้นท้องเรียบ มอก.",
    subLabel: "มาตรฐานอุตสาหกรรม",
    category: "slabs",
    categoryLabel: "กลุ่มราคาแผ่นพื้นคอนกรีตอัดแรง (บาท / ตร.ม.)",
    unit: "บ./ตร.ม.",
    priceKey: "mocBoardPrice",
    costKey: "mocBoardPrice",
    weightKey: "slab",
    weightUnit: "กก./ตร.ม.",
    isTIS: true,
  },
  {
    id: "hcPriceSqm",
    name: "แผ่นพื้นกลวง Hollow Core",
    subLabel: "ความหนามาตรฐาน",
    category: "slabs",
    categoryLabel: "กลุ่มราคาแผ่นพื้นคอนกรีตอัดแรง (บาท / ตร.ม.)",
    unit: "บ./ตร.ม.",
    priceKey: "hcPriceSqm",
    costKey: "hcPriceSqm",
    fixedWeight: 115,
    weightUnit: "กก./ตร.ม.",
  },

  // 2. Hex and Fence
  {
    id: "hexPilePrice",
    name: "เสาเข็มหกเหลี่ยมกลวง",
    subLabel: "Hex Pile",
    category: "hex_fence",
    categoryLabel: "เสาเข็มหกเหลี่ยม & เสารั้ว (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "hexPilePrice",
    costKey: "hexPilePrice",
    weightKey: "hex",
    weightUnit: "กก./ม.",
  },
  {
    id: "fence3Price",
    name: "เสารั้วลวดหนาม 3 นิ้ว",
    subLabel: "หน้าตัด 3 นิ้ว",
    category: "hex_fence",
    categoryLabel: "เสาเข็มหกเหลี่ยม & เสารั้ว (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "fence3Price",
    costKey: "fence3Price",
    weightKey: "fence3",
    weightUnit: "กก./ม.",
  },
  {
    id: "fence4Price",
    name: "เสารั้วลวดหนาม 4 นิ้ว",
    subLabel: "หน้าตัด 4 นิ้ว",
    category: "hex_fence",
    categoryLabel: "เสาเข็มหกเหลี่ยม & เสารั้ว (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "fence4Price",
    costKey: "fence4Price",
    weightKey: "fence4",
    weightUnit: "กก./ม.",
  },

  // 3. I-Shape Piles
  {
    id: "i15Price",
    name: "เสาเข็มไอ I-15",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i15Price",
    costKey: "i15Price",
    weightKey: "i15",
    weightUnit: "กก./ม.",
  },
  {
    id: "i18NoTISPrice",
    name: "เสาเข็มไอ I-18 ธรรมดา",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i18NoTISPrice",
    costKey: "i18NoTISPrice",
    weightKey: "i18_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i18TISPrice",
    name: "เสาเข็มไอ I-18 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i18TISPrice",
    costKey: "i18TISPrice",
    weightKey: "i18_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i18JointPrice",
    name: "เสาเข็มไอ I-18 ธรรมดา",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i18JointPrice",
    costKey: "i18JointPrice",
    weightKey: "i18_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i18TISJointPrice",
    name: "เสาเข็มไอ I-18 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i18TISJointPrice",
    costKey: "i18TISJointPrice",
    weightKey: "i18_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i22NoTISPrice",
    name: "เสาเข็มไอ I-22 ธรรมดา",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i22NoTISPrice",
    costKey: "i22NoTISPrice",
    weightKey: "i22_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i22TISPrice",
    name: "เสาเข็มไอ I-22 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i22TISPrice",
    costKey: "i22TISPrice",
    weightKey: "i22_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i22JointPrice",
    name: "เสาเข็มไอ I-22 ธรรมดา",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i22JointPrice",
    costKey: "i22JointPrice",
    weightKey: "i22_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i22TISJointPrice",
    name: "เสาเข็มไอ I-22 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i22TISJointPrice",
    costKey: "i22TISJointPrice",
    weightKey: "i22_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i26NoTISPrice",
    name: "เสาเข็มไอ I-26 ธรรมดา",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i26NoTISPrice",
    costKey: "i26NoTISPrice",
    weightKey: "i26_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i26NoTISJointPrice",
    name: "เสาเข็มไอ I-26 ธรรมดา",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i26NoTISJointPrice",
    costKey: "i26NoTISJointPrice",
    weightKey: "i26_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i26TISPrice",
    name: "เสาเข็มไอ I-26 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i26TISPrice",
    costKey: "i26TISPrice",
    weightKey: "i26_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i26TISJointPrice",
    name: "เสาเข็มไอ I-26 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i26TISJointPrice",
    costKey: "i26TISJointPrice",
    weightKey: "i26_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i30NoTISPrice",
    name: "เสาเข็มไอ I-30 ธรรมดา",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i30NoTISPrice",
    costKey: "i30NoTISPrice",
    weightKey: "i30_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i30NoTISJointPrice",
    name: "เสาเข็มไอ I-30 ธรรมดา",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i30NoTISJointPrice",
    costKey: "i30NoTISJointPrice",
    weightKey: "i30_no_tis",
    weightUnit: "กก./ม.",
  },
  {
    id: "i30TISPrice",
    name: "เสาเข็มไอ I-30 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i30TISPrice",
    costKey: "i30TISPrice",
    weightKey: "i30_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i30TISJointPrice",
    name: "เสาเข็มไอ I-30 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i30TISJointPrice",
    costKey: "i30TISJointPrice",
    weightKey: "i30_tis",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i35TISPrice",
    name: "เสาเข็มไอ I-35 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i35TISPrice",
    costKey: "i35TISPrice",
    weightKey: "i35",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i35TISJointPrice",
    name: "เสาเข็มไอ I-35 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i35TISJointPrice",
    costKey: "i35TISJointPrice",
    weightKey: "i35",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i40TISPrice",
    name: "เสาเข็มไอ I-40 มอก.",
    subLabel: "ท่อนเดียว (Single)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i40TISPrice",
    costKey: "i40TISPrice",
    weightKey: "i40",
    weightUnit: "กก./ม.",
    isTIS: true,
  },
  {
    id: "i40TISJointPrice",
    name: "เสาเข็มไอ I-40 มอก.",
    subLabel: "ท่อนต่อ (Joint)",
    category: "i_piles",
    categoryLabel: "กลุ่มเสาเข็มรูปตัวไอ I-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "i40TISJointPrice",
    costKey: "i40TISJointPrice",
    weightKey: "i40",
    weightUnit: "กก./ม.",
    isTIS: true,
  },

  // 4. S-Shape Piles (Solid Square Piles)
  {
    id: "s18Price",
    name: "เสาเข็มสี่เหลี่ยม S-18",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s18Price",
    costKey: "s18Price",
    weightKey: "s18",
    weightUnit: "กก./ม.",
  },
  {
    id: "s18JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-18",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s18JointPrice",
    costKey: "s18JointPrice",
    weightKey: "s18",
    weightUnit: "กก./ม.",
  },
  {
    id: "s22Price",
    name: "เสาเข็มสี่เหลี่ยม S-22",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s22Price",
    costKey: "s22Price",
    weightKey: "s22",
    weightUnit: "กก./ม.",
  },
  {
    id: "s22JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-22",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s22JointPrice",
    costKey: "s22JointPrice",
    weightKey: "s22",
    weightUnit: "กก./ม.",
  },
  {
    id: "s26Price",
    name: "เสาเข็มสี่เหลี่ยม S-26",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s26Price",
    costKey: "s26Price",
    weightKey: "s26",
    weightUnit: "กก./ม.",
  },
  {
    id: "s26JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-26",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s26JointPrice",
    costKey: "s26JointPrice",
    weightKey: "s26",
    weightUnit: "กก./ม.",
  },
  {
    id: "s30Price",
    name: "เสาเข็มสี่เหลี่ยม S-30",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s30Price",
    costKey: "s30Price",
    weightKey: "s30",
    weightUnit: "กก./ม.",
  },
  {
    id: "s30JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-30",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s30JointPrice",
    costKey: "s30JointPrice",
    weightKey: "s30",
    weightUnit: "กก./ม.",
  },
  {
    id: "s35Price",
    name: "เสาเข็มสี่เหลี่ยม S-35",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s35Price",
    costKey: "s35Price",
    weightKey: "s35",
    weightUnit: "กก./ม.",
  },
  {
    id: "s35JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-35",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s35JointPrice",
    costKey: "s35JointPrice",
    weightKey: "s35",
    weightUnit: "กก./ม.",
  },
  {
    id: "s40Price",
    name: "เสาเข็มสี่เหลี่ยม S-40",
    subLabel: "ท่อนเดียว",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s40Price",
    costKey: "s40Price",
    weightKey: "s40",
    weightUnit: "กก./ม.",
  },
  {
    id: "s40JointPrice",
    name: "เสาเข็มสี่เหลี่ยม S-40",
    subLabel: "ท่อนต่อ (Joint)",
    category: "s_piles",
    categoryLabel: "กลุ่มเสาเข็มสี่เหลี่ยมตัน S-Shape (บาท / เมตร)",
    unit: "บ./ม.",
    priceKey: "s40JointPrice",
    costKey: "s40JointPrice",
    weightKey: "s40",
    weightUnit: "กก./ม.",
  },

  // 5. Pipes (ท่อระบายน้ำ คสล.)
  {
    id: "pipe030NoTISPrice",
    name: "ท่อ คสล. Ø 0.30 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe030NoTISPrice",
    costKey: "pipe030NoTISPrice",
    weightKey: "pipe030Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe030T3Price",
    name: "ท่อ คสล. Ø 0.30 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe030T3Price",
    costKey: "pipe030T3Price",
    weightKey: "pipe030T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe030T2Price",
    name: "ท่อ คสล. Ø 0.30 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe030T2Price",
    costKey: "pipe030T2Price",
    weightKey: "pipe030T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe040NoTISPrice",
    name: "ท่อ คสล. Ø 0.40 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe040NoTISPrice",
    costKey: "pipe040NoTISPrice",
    weightKey: "pipe040Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe040T3Price",
    name: "ท่อ คสล. Ø 0.40 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe040T3Price",
    costKey: "pipe040T3Price",
    weightKey: "pipe040T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe040T2Price",
    name: "ท่อ คสล. Ø 0.40 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe040T2Price",
    costKey: "pipe040T2Price",
    weightKey: "pipe040T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe050NoTISPrice",
    name: "ท่อ คสล. Ø 0.50 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe050NoTISPrice",
    costKey: "pipe050NoTISPrice",
    weightKey: "pipe050Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe050T3Price",
    name: "ท่อ คสล. Ø 0.50 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe050T3Price",
    costKey: "pipe050T3Price",
    weightKey: "pipe050T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe050T2Price",
    name: "ท่อ คสล. Ø 0.50 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe050T2Price",
    costKey: "pipe050T2Price",
    weightKey: "pipe050T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe060NoTISPrice",
    name: "ท่อ คสล. Ø 0.60 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe060NoTISPrice",
    costKey: "pipe060NoTISPrice",
    weightKey: "pipe060Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe060T3Price",
    name: "ท่อ คสล. Ø 0.60 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe060T3Price",
    costKey: "pipe060T3Price",
    weightKey: "pipe060T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe060T2Price",
    name: "ท่อ คสล. Ø 0.60 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe060T2Price",
    costKey: "pipe060T2Price",
    weightKey: "pipe060T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe080NoTISPrice",
    name: "ท่อ คสล. Ø 0.80 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe080NoTISPrice",
    costKey: "pipe080NoTISPrice",
    weightKey: "pipe080Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe080T3Price",
    name: "ท่อ คสล. Ø 0.80 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe080T3Price",
    costKey: "pipe080T3Price",
    weightKey: "pipe080T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe080T2Price",
    name: "ท่อ คสล. Ø 0.80 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe080T2Price",
    costKey: "pipe080T2Price",
    weightKey: "pipe080T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe100NoTISPrice",
    name: "ท่อ คสล. Ø 1.00 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe100NoTISPrice",
    costKey: "pipe100NoTISPrice",
    weightKey: "pipe100Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe100T3Price",
    name: "ท่อ คสล. Ø 1.00 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe100T3Price",
    costKey: "pipe100T3Price",
    weightKey: "pipe100T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe100T2Price",
    name: "ท่อ คสล. Ø 1.00 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe100T2Price",
    costKey: "pipe100T2Price",
    weightKey: "pipe100T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe120NoTISPrice",
    name: "ท่อ คสล. Ø 1.20 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe120NoTISPrice",
    costKey: "pipe120NoTISPrice",
    weightKey: "pipe120Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe120T3Price",
    name: "ท่อ คสล. Ø 1.20 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe120T3Price",
    costKey: "pipe120T3Price",
    weightKey: "pipe120T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe120T2Price",
    name: "ท่อ คสล. Ø 1.20 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe120T2Price",
    costKey: "pipe120T2Price",
    weightKey: "pipe120T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe150NoTISPrice",
    name: "ท่อ คสล. Ø 1.50 ม. ธรรมดา",
    subLabel: "ปากลิ้นราง ยาว 1 ม.",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe150NoTISPrice",
    costKey: "pipe150NoTISPrice",
    weightKey: "pipe150Weight",
    weightUnit: "กก./ท่อน",
  },
  {
    id: "pipe150T3Price",
    name: "ท่อ คสล. Ø 1.50 ม. มอก.3",
    subLabel: "มาตรฐาน มอก. ชั้น 3",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe150T3Price",
    costKey: "pipe150T3Price",
    weightKey: "pipe150T3Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },
  {
    id: "pipe150T2Price",
    name: "ท่อ คสล. Ø 1.50 ม. มอก.2",
    subLabel: "มาตรฐาน มอก. ชั้น 2 (งานทางหลวง)",
    category: "pipes",
    categoryLabel: "กลุ่มท่อระบายน้ำ คสล. (บาท / ท่อน)",
    unit: "บ./ท่อน",
    priceKey: "pipe150T2Price",
    costKey: "pipe150T2Price",
    weightKey: "pipe150T2Weight",
    weightUnit: "กก./ท่อน",
    isTIS: true,
  },

  // 6. Basins (บ่อพัก คสล.)
  {
    id: "basin030Price",
    name: "บ่อพัก คสล. ขนาด 0.30 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 30 ซม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin030Price",
    costKey: "basin030Price",
    weightKey: "basin030Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin040Price",
    name: "บ่อพัก คสล. ขนาด 0.40 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 40 ซม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin040Price",
    costKey: "basin040Price",
    weightKey: "basin040Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin050Price",
    name: "บ่อพัก คสล. ขนาด 0.50 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 50 ซม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin050Price",
    costKey: "basin050Price",
    weightKey: "basin050Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin060Price",
    name: "บ่อพัก คสล. ขนาด 0.60 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 60 ซม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin060Price",
    costKey: "basin060Price",
    weightKey: "basin060Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin080Price",
    name: "บ่อพัก คสล. ขนาด 0.80 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 80 ซม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin080Price",
    costKey: "basin080Price",
    weightKey: "basin080Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin100Price",
    name: "บ่อพัก คสล. ขนาด 1.00 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 1.00 ม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin100Price",
    costKey: "basin100Price",
    weightKey: "basin100Weight",
    weightUnit: "กก./ชิ้น",
  },
  {
    id: "basin120Price",
    name: "บ่อพัก คสล. ขนาด 1.20 ม.",
    subLabel: "สำหรับท่อระบายน้ำ 1.20 ม.",
    category: "basins",
    categoryLabel: "กลุ่มบ่อพัก คสล. (บาท / ชิ้น)",
    unit: "บ./ชิ้น",
    priceKey: "basin120Price",
    costKey: "basin120Price",
    weightKey: "basin120Weight",
    weightUnit: "กก./ชิ้น",
  },
];

/**
 * Returns unified list of products, taking into account current prices, costs, weights,
 * user-added custom products, and filtering out any deleted products.
 */
export function getUnifiedCatalog(
  settings: AppSettings,
  pricesInput?: Prices,
  costsInput?: Prices,
  weightsInput?: Weights,
  customProductsInput?: CustomProduct[],
  deletedItemIdsInput?: string[]
): UnifiedCatalogItem[] {
  const currentPrices = pricesInput || settings.prices;
  const currentCosts = costsInput || settings.costs || settings.prices;
  const currentWeights = weightsInput || settings.weights;
  const customProducts = customProductsInput || settings.customProducts || [];
  const deletedIds = new Set(deletedItemIdsInput || settings.deletedItemIds || []);

  const items: UnifiedCatalogItem[] = [];

  // 1. Standard Products (excluding deleted)
  for (const std of STANDARD_PRODUCTS) {
    if (deletedIds.has(std.id)) continue;

    const price = currentPrices[std.priceKey] || 0;
    const cost = currentCosts[std.costKey] || 0;
    const markup = Math.max(0, Number((price - cost).toFixed(2)));
    const weight = std.weightKey
      ? currentWeights[std.weightKey] || 0
      : (std.fixedWeight || 0);

    items.push({
      id: std.id,
      name: std.name,
      subLabel: std.subLabel,
      category: std.category,
      categoryLabel: std.categoryLabel,
      unit: std.unit,
      cost,
      price,
      markup,
      weight,
      weightUnit: std.weightUnit,
      isTIS: std.isTIS,
      isCustom: false,
      fieldKey: std.priceKey,
      weightKey: std.weightKey,
    });
  }

  // 2. Custom Products (excluding deleted)
  for (const cp of customProducts) {
    if (deletedIds.has(cp.id)) continue;

    const cost = cp.cost || 0;
    const price = cp.price || 0;
    const markup = cp.markup !== undefined ? cp.markup : Math.max(0, Number((price - cost).toFixed(2)));

    const catDef = CATEGORY_DEFINITIONS.find((c) => c.id === cp.category);
    const categoryLabel = catDef ? `กลุ่ม${catDef.label} (สินค้าสั่งทำ/กำหนดเอง)` : "สินค้าสั่งทำ / กำหนดเอง";

    items.push({
      id: cp.id,
      name: cp.name,
      subLabel: cp.subLabel || "สินค้ากำหนดเอง",
      category: cp.category,
      categoryLabel,
      unit: cp.unit || "บ./ชิ้น",
      cost,
      price,
      markup,
      weight: cp.weight || 0,
      weightUnit: cp.weightUnit || "กก./ชิ้น",
      isTIS: cp.isTIS,
      isCustom: true,
    });
  }

  return items;
}

/**
 * Returns list of deleted products so the user can easily review and restore them.
 */
export function getDeletedCatalogItems(
  settings: AppSettings,
  deletedItemIdsInput?: string[]
): UnifiedCatalogItem[] {
  const deletedIds = new Set(deletedItemIdsInput || settings.deletedItemIds || []);
  if (deletedIds.size === 0) return [];

  const deletedItems: UnifiedCatalogItem[] = [];

  // Check standard items
  for (const std of STANDARD_PRODUCTS) {
    if (deletedIds.has(std.id)) {
      const price = settings.prices[std.priceKey] || 0;
      const cost = (settings.costs && settings.costs[std.costKey]) || 0;
      const weight = std.weightKey
        ? settings.weights[std.weightKey] || 0
        : (std.fixedWeight || 0);

      deletedItems.push({
        id: std.id,
        name: std.name,
        subLabel: std.subLabel,
        category: std.category,
        categoryLabel: std.categoryLabel,
        unit: std.unit,
        cost,
        price,
        markup: Math.max(0, Number((price - cost).toFixed(2))),
        weight,
        weightUnit: std.weightUnit,
        isTIS: std.isTIS,
        isCustom: false,
        fieldKey: std.priceKey,
        weightKey: std.weightKey,
      });
    }
  }

  // Check custom items
  const customProducts = settings.customProducts || [];
  for (const cp of customProducts) {
    if (deletedIds.has(cp.id)) {
      deletedItems.push({
        id: cp.id,
        name: cp.name,
        subLabel: cp.subLabel,
        category: cp.category,
        categoryLabel: "สินค้ากำหนดเอง",
        unit: cp.unit,
        cost: cp.cost,
        price: cp.price,
        markup: cp.markup || 0,
        weight: cp.weight,
        weightUnit: cp.weightUnit,
        isTIS: cp.isTIS,
        isCustom: true,
      });
    }
  }

  return deletedItems;
}

/**
 * Get weight options for WeightCalculator, including active custom products
 * and filtering out deleted products.
 */
export function getDynamicWeightOptions(settings: AppSettings) {
  const deletedIds = new Set(settings.deletedItemIds || []);
  const catalog = getUnifiedCatalog(settings);

  return catalog.map((item) => ({
    value: item.id,
    label: `${item.name}${item.subLabel ? ` (${item.subLabel})` : ""}${item.isTIS ? " [มอก.]" : ""}`,
    weight: item.weight,
    unit: item.unit,
    weightUnit: item.weightUnit,
    category: item.category,
    isCustom: item.isCustom,
    isPerPiece: item.weightUnit.includes("ท่อน") || item.weightUnit.includes("ชิ้น") || item.category === "pipes" || item.category === "basins",
  }));
}
